### ISSUE TITLE
`babashka.fs/glob` does not find directories with `.` in the name

### ISSUE THREAD

**Issue by leifericf** [babashka/fs#105]
I'm replacing a Bash script that contains the following line:

`find ./repos -name ".git" -type d`

Output:

```bash
./repos/some-repo/.git
./repos/my-other-repo/.git
./repos/yet-another-repo/.git
[...]
```

It finds all directories named `.git`

Notice that `.git` is an "invisible directory" beginning with `.`

Using Babashka, I tried this:

```clojure
(defn find-repos
  "Find all Git repos in a directory."
  [root-path] (babashka.fs/glob root-path "**.git"))

(find-repos "./repos") => []
```

`./repos` contains several Git repositories, yet `babashka.fs/glob` returns an empty vector.

Relevant info from @borkdude, copied from Slack:

> Good point. I think this is because `visit-file` is never called on a directory:
> 
> ```clojure
> (fs/walk-file-tree "."
>                    {:pre-visit-dir (fn [dir _]
>                                      #_(when (str/includes? (str dir) ".git")
>                                        (prn dir)) :continue)
>                     :visit-file (fn [path attrs]
>                                   (when (and (fs/directory? path)
>                                              (str/includes? (str path) ".git"))
>                                     (prn path))
>                                   :continue)})
> ```
> 
> And match is only ever called on files here:
> 
> https://github.com/babashka/fs/blob/c5c5365585efa44a6c4e8ca91bd84d9adc631a02/src/babashka/fs.cljc#L314
> 
> Feel free to file a bug report.

Digging a bit deeper, I discovered something interesting…

This works:

```clojure
(babashka.fs/create-dir "./test-dir")
(babashka.fs/glob "." "**test-dir") => [#object[sun.nio.fs.UnixPath 0x35cba6ab "test-dir"]]
```

But this does not:

```clojure
(babashka.fs/create-dir "./.test-dir")
(babashka.fs/glob "." "**.test-dir") => []
```

Could it perhaps have something to do with the `.` in the directory name?

**Comment by bobisageek** [comment]
most *nixes treat files/directories starting with a dot as 'hidden':
```shell
$ find ./repos -name '*p' -type d
./repos/pl.lp
./repos/plop
./repos/.plup
./repos/plip
```

`fs/glob` takes a `:hidden` option to include hidden files:
```clj
;  helper function to just get names
user=> (defn path-names [ps] (map (comp #(.getName %) fs/file) ps))
#'user/path-names

; doesn't return 'hidden' files/dirs (in this case, the dir whose name starts with a dot)
user=> (->> (fs/glob "./repos" "**p" ) path-names)
("pl.lp" "plop" "plip")

; add the option from the docs
user=> (->> (fs/glob "./repos" "**p" {:hidden true}) path-names)
("pl.lp" "plop" ".plup" "plip")
```

**Comment by borkdude** [comment]
Yeah, you must scan the hidden folders to find `.git`:

``` clojure
(require '[babashka.fs :as fs])

(defn find-repos
  "Find all Git repos in a directory."
  [root-path] (babashka.fs/glob root-path "**.git" {:hidden true}))

(prn (find-repos (first *command-line-args*)))
```

Hope that helps.

**Comment by leifericf** [comment]
Gotcha, thanks! That worked like a charm.
