### ISSUE TITLE
suggestion: fs/find-up

### ISSUE THREAD

**Issue by eval** [babashka/fs#112]
When writing bb-scripts operating on files I often find myself writing code related to 
A) finding a specific file that I'm sure exists in CWD or a parent folder (e.g. "deps.edn", "README.md" when writing a project-script) or 
B) finding a folder for which some condition holds (for generic scripts e.g. to determine if you're in a Clojure-project, or the folder contains a README-like file).

I imagine an fn `find-up` that helps in both these cases:
```clojure
;; A)
(find-up "README.md") ;; => full-path of found README.md else nil
(find-up "subproject/deps.edn")

;; B)
;; looking for a README-like
(let [readme-like #(first (glob % "README*"))]
  (some-> (find-up readme-like) readme-like))
```

Neat?

**Comment by borkdude** [comment]
What about passing an explicit directory from where to search up?
I have a function in clj-kondo where I needed that: https://github.com/clj-kondo/clj-kondo/blob/8d1531b23485815ab26a7da10eac9950ecc2338d/src/clj_kondo/impl/core.clj#L199-L218

Some alternatives: lazy sequence of all matches going up, could also be another function `find-up-all` or so.

**Comment by eval** [comment]
> What about passing an explicit directory from where to search up?

Indeed. Will draft something, also to see the edgecases...

> Some alternatives: lazy sequence of all matches going up, could also be another function find-up-all or so.

Could be possible with `(iterate #(fs/find-up "foo" %) (fs/cwd))` but otherwise dedicated fn indeed.

**Comment by borkdude** [comment]
Another approach could just be to split this function into multiple smaller primitives, like `fs/parents` after which it's pretty easy to find matching files in each directory above:

```
(require '[babashka.fs :as fs])

(defn absolute-parent [x]
  (some-> x fs/absolutize fs/parent str))

(def parent-dirs (take-while some? (iterate absolute-parent (absolute-parent "."))))

(def git-ignores (keep #(let [git-ignore (fs/path % ".gitignore")]
                          (when (fs/exists? git-ignore) (str git-ignore))) parent-dirs))
(prn git-ignores)
```

**Comment by teodorlu** [comment]
This kind of feels like an inverse to `fs/glob` to me.

Perhaps something like this could do the trick:

```
(fs/glob-up "." "**/deps.edn" {:max-depth 3})
;; "." => start at the current directory
;; "**/deps.edn" => match deps.edn files in all directories searched
;; {:max-depth 3} => go a maximum of 3 levels up
```

I'd expect `fs/glob-up` to only match in parent directories. So

```
(fs/glob-up (fs/path (fs/expand-home "~") "dev" "babashka" "fs") "**/*.edn" {:max-depth 2})
```

should match all EDN files in `~/dev/babashka/fs`, `~/dev/babashka` and `~/dev`.

I'm not quite sure about the name `:max-depth`, but I don't have any other options.

**Comment by borkdude** [comment]
I've seen another variation of `find-up` recently which had slightly other requirements than the proposed version. That confirmed me in my feelings that this function shouldn't yet be in fs itself, but just implemented in user space since there is no commonly agreed understanding of what this function should do.
