### ISSUE TITLE
glob: hidden-option based on pattern

### ISSUE THREAD

**Issue by eval** [babashka/fs#113]
Could the hidden-option for [glob](https://github.com/babashka/fs/blob/master/API.md#babashka.fs/glob) be enabled when it's not explicitly provided and the pattern starts with "."?  e.g. `(glob (home) ".git*")` finds git config-files.  
This would be similar to what happens with the `recursive`-option.  
Happy to submit a PR!

**Comment by borkdude** [comment]
`:hidden true`

**Comment by borkdude** [comment]
oh when it's not explicitly provided, I see. yeah, that probably makes sense.
