### ISSUE TITLE
weird behaviour fs/match, fs/glob

### ISSUE THREAD

**Issue by jave** [babashka/fs#121]
```
$ cd /

23:34:11-joakim@genos:/
$ bb

Babashka v1.3.186 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (fs/match "." "regex:.*")
[#object[sun.nio.fs.UnixPath 0x32eeff23 "bin"] #object[sun.nio.fs.UnixPath 0x56bb1954 "lib"] #object[sun.nio.fs.UnixPath 0x27dbd3af "lib64"] #object[sun.nio.fs.UnixPath 0x2dc7b200 "sbin"]]
user=> 23:34:36-joakim@genos:/
$ ls

afs  bin  boot  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

I tried this with both glob and match (glob calls match).  I'm expecting all the dirs show up in the return value of match or glob, but here only a couple show up.

**Comment by borkdude** [comment]
I think glob and match only return non-directory files. The return values above might be symlinks that point to another directory?

**Comment by borkdude** [comment]
It might actually be goods to return directories as well if they match the glob. Just never has come up so far.

**Comment by jave** [comment]
yes you are right, symlinks and files show up. I didnt consider that they might be symlinks.

in my case I guess I can use file-seq, but that seems to be recursive by defauly, which I didnt want in this case, I only wanted to have a simple glob

**Comment by borkdude** [comment]
You can use fs/list-dir

https://www.michielborkent.nl
https://www.eetvoorjeleven.nu

**Comment by borkdude** [comment]
Actually I was wrong about not matching directories: fs/glob + fs/match do match directories but you have to provide a max-depth:

```
 $ bb -e '(map str (filter fs/directory? (fs/glob "." "*" {:max-depth 1})))'
("home" "usr" "nix" "bin" "sbin" "etc" "var" "Library" "System" "private" "Users" "Applications" "opt" "dev" "Volumes" "tmp" "cores")
```

**Comment by borkdude** [comment]
Also it supports the `:follow-links` option for following symlinks.

**Comment by borkdude** [comment]
For simply listing all files in a directory, I'd still use `fs/list-dir`.

**Comment by jave** [comment]
thanks
