### ISSUE TITLE
copy-tree fail when some non-leaf directories in the tree are not writable

### ISSUE THREAD

**Issue by Sohalt** [babashka/fs#122]
Given something like:
```sh
mkdir -p src/a/b
chmod -R 555 src
```
trying to do
```clojure
(fs/copy-tree "src" "dst")
```
fails with
```
Type:     java.nio.file.AccessDeniedException
Message:  /dst/a/b
```
and afaics explicitlty passing `:posix-file-permissions` also doesn't help.

Regular. `cp -r src dest` works. I assume it creates the destination tree writable and only afterwards sets the permissions like found on the source.

**Comment by borkdude** [comment]
Nice edge case. Any suggestions for a fix?

**Comment by Sohalt** [comment]
Always creating directories with 7xx permissions and adjusting the permissions in `post-visit-dir`?
Not sure you have access to the info there though.

**Comment by Sohalt** [comment]
I'll give it a quick try and see if I can fix it.
