### ISSUE TITLE
Potential regression

### ISSUE THREAD

**Issue by lispyclouds** [babashka/fs#126]
Found this error when using bb master builds and I think it could be a regression from https://github.com/babashka/fs/commit/13484934fdf47d25d4243b36abd4b2b81e1a7bdd

minimal repro:

Download this zip: https://github.com/catppuccin/gtk/releases/download/v0.7.3/Catppuccin-Mocha-Standard-Blue-Dark.zip

```clojure
(require '[babashka.fs :as fs])

(fs/unzip "archive.zip" "." {:replace-existing true})
```

should produce:
```
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalArgumentException
Message:  No matching field found: close for class sun.nio.ch.ChannelInputStream
Location: /home/lispyclouds/foo.clj:3:1

----- Context ------------------------------------------------------------------
1: (require '[babashka.fs :as fs])
2:
3: (fs/unzip "archive.zip" "." {:replace-existing true})
   ^--- No matching field found: close for class sun.nio.ch.ChannelInputStream

----- Stack trace --------------------------------------------------------------
babashka.fs/unzip - <built-in>
user              - /home/lispyclouds/foo.clj:3:1
```

works fine with the current released bb

**Comment by borkdude** [comment]
Probably introduced here by this commit https://github.com/babashka/fs/commit/13484934fdf47d25d4243b36abd4b2b81e1a7bdd

Not sure why there wasn't a test that caught this?

cc @Sohalt

**Comment by borkdude** [comment]
When loading fs I get this:

```
user=> (require '[babashka.fs :as fs])
Reflection warning, babashka/fs.cljc:971:6 - reference to field close can't be resolved.
```

**Comment by borkdude** [comment]
Fixed the reflection issue and bumped fs in bb. Please try again when CI is finished, I expect it to be fixed now.

**Comment by lispyclouds** [comment]
Works now!
