### ISSUE TITLE
expand-home

### ISSUE THREAD

**Issue by borkdude** [babashka/fs#13]
Should we add an expand-home function that expands a leading `~` into `(System/getProperty "user.home")`?

Questions:

- On Windows this doesn't mean anything. Should we also read `~/foo/bar` as `C:\Users\borkdude\foo\bar` on Windows
- Do we need to expand more than tilde?
- Do we need to expand tilde is if's not the leading character?

**Comment by frou** [comment]
As some precedent, Python's similar function does expand `~` on Windows. [The mechanism is described here](https://docs.python.org/3/library/os.path.html#os.path.expanduser)

**Comment by Kineolyan** [comment]
Would you accept a PR adding this function?
I found myself migrating a personal project to _babashka.fs_ instead of _clj-commons/fs_ and it was the only function I was missing, while I was glad to find many new methods, like `path`.

**Comment by borkdude** [comment]
@Kineolyan OK, let's go ahead. Please also add tests.

**Comment by Kineolyan** [comment]
Ok, thanks. I'll try to do it this week

**Comment by Kineolyan** [comment]
Because this is related, I am also working on #12  :)
