### ISSUE TITLE
Feature request: Extension utils

### ISSUE THREAD

**Issue by kiramclean** [babashka/fs#19]
This seems to most up-to-date JVM Clojure filesystem library, but I noticed there are couple of differences from some of the other ones. I was wondering what you think of adding extension utils to this library, like `split-ext` or `ext`, like ones from e.g. the [clj-commons lib](https://github.com/clj-commons/fs/blob/686e52b6c533b2ed5a60458b9c6f07d3e42c5ebf/src/me/raynes/fs.clj#L206-L217).

They're really simple so maybe it doesn't make sense to include here. Or maybe you want to stick to mirroring the java file APIs. Anyway, I can see why they might not belong here, but if this is something you'd consider I'd be happy to help implement it.

Thanks for yet another useful library!

**Comment by borkdude** [comment]
@kiramclean I'm fine with adding that. PR welcome. As a rule of thumb, I try to stick to the naming of the Java NIO api but I don't think there is such a function in the Java NIO API currently.

**Comment by kiramclean** [comment]
Cool! Yeah as far as I could tell there's no built-in way to do it with Java NIO.

**Comment by kiramclean** [comment]
Do you have an opinion about whether multiple extensions should be grouped with the name or the extension? E.g.

1:
```clj
(split-ext "index.html.template") => ["index" "html.template"]
```

vs. 2:
```clj
(split-ext "index.html.template") => ["index.html" "template"]
```

I think I favour #1 because it seems like returning a vector of `[name ext]` makes sense, so the `name` part should be the same as whatever `fs/file-name` returns. But happy to do it either way.

**Comment by borkdude** [comment]
I think returning a vector of the name without ext + the ext makes sense. 

Let's consider: `foo.bar.jpg`. Isn't the extension `jpg` here?

**Comment by kiramclean** [comment]
Ah yeah you're right.. #1 would totally not work. File names with `.` in are valid file names 🤦‍♀️
