### ISSUE TITLE
Wrap fs/create-dir with fs/exists?

### ISSUE THREAD

**Issue by lhrb** [babashka/fs#21]
Hey, I really like the `babshka.fs` namespace, thanks for creating.

In my scripts I tend to wrap `create-dir` like this   

```clojure
(defn create-dir [path]
  (when-not (fs/exists? path)
    (fs/create-dir path)))
```

Just wanted to check if you think this would be a useful addition to the `babshka.fs` namespace?

**Comment by borkdude** [comment]
In this case you might want to use `create-dirs` which does not throw. The behavior of `create-dir` is the same as the underlying Java method.

**Comment by borkdude** [comment]
And thanks!

**Comment by lhrb** [comment]
TIL! Thank you.
