### ISSUE TITLE
Feature request expose what "pattern" is passed to getPathMatcher (glob function)

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/fs#32]
I found myself wanting to put "regex" pattern instead of "glob".
Cheers.

**Comment by borkdude** [comment]
@benjamin-asdf Worth mentioning that you can use this library from source in babashka if you add it to your deps and load it with `:reload`:

```
$ bb -cp src -e "(ns foo (:require [babashka.fs :as fs] :reload))" -e '(fs/match "." "regex:README.*")'
[#object[sun.nio.fs.UnixPath 0x1256d66e "README.md"]]
```
