### ISSUE TITLE
Clarify posix-file-permissions option

### ISSUE THREAD

**Issue by borkdude** [babashka/fs#36]
heow Today at 3:42 PM
anyone know the permissions format for (fs/create-dir "foo") ?  The docs just reference Files which is a bit opaque

3 replies
borkdude:clj-kondo:  3 minutes ago
The docs could be improved here. In another function I see:
The :posix-file-permissions option is a string like "rwx------"
:+1:
1

borkdude:clj-kondo:  1 minute ago
Please post an issue about this.
borkdude:clj-kondo:  < 1 minute ago
Or I will do this myself now, actually ;).

**Comment by teodorlu** [comment]
Was this solved in https://github.com/babashka/fs/pull/128 ?
