### ISSUE TITLE
Add fs/zip

### ISSUE THREAD

**Issue by borkdude** [babashka/fs#41]
We can look at the tools build implementation for this as an example.

**Comment by borkdude** [comment]
https://gist.github.com/borkdude/b880118c78ac2dc0a95fd287fd638841

**Comment by borkdude** [comment]
There are many choices that one can make. I have one possible choice in a `zip` branch.

- Should `(fs/zip "foo.zip" ["src"])` preserve `src` itself in the zip file? The unix `zip` does this by default, but Python's `shutil.make_archive(output_filename, 'zip', dir_name)` does not. tools.build's `zip` also doesn't.

/cc @lispyclouds @lread

**Comment by lread** [comment]
And then there is [clj-commons/fs approach](https://cljdoc.org/d/clj-commons/fs/1.6.310/api/me.raynes.fs.compression#zip) which gets pretty specific. You specify the desired zip path for each file. 

The naming of `make-archive` is interestingly vague and allows support for other compression formats.

But back to your question. I think as long as you document clearly, both are OK choices.
If we look at the current API's unzip, it can specify an optional dest root, I suppose zip could do the same?

Is zip going to allow excluding of hidden files like `.DS_Store` on macOS?

**Comment by borkdude** [comment]
Maybe we should list other alternatives from other scripting languages/environments too. Ignoring certain files seems good.

**Comment by lread** [comment]
I don't expect `babashka/fs` to support this but it is also interesting to scope things out (as in won't do): An interesting feature of the `clj-commons/fs` compression is streaming support.  This seems to allow, for example, a webserver to deliver a zip file without first creating it on the file system.

**Comment by lread** [comment]
Yeah, very good, that sounds like the appropriate tone to me.

**Comment by borkdude** [comment]
For babashka's own (and related) projects it is pretty common to zip just one file. On Windows, in the absence of `zip.exe` or so, I used `java -jar` for this:

https://github.com/babashka/babashka/blob/f620a3dde9e6ea23d35a3f56cc669f0f8721d323/appveyor.yml#L63

**Comment by corasaurus-hex** [comment]
A very explicit (but less convenient) version might look like:

```clojure
(fs/zip-entries "foo.zip" [{:local-path "src/babashka/fs.clj" :zip-path "babashka/fs.clj"}
                           {:local-path "resources/index.html" :zip-path "index.html"}])
```

Where each map in the vec is a [ZipEntry](https://github.com/babashka/fs/commit/0222dba20f9babc032f79c2c0c008471f164ec28#diff-412a82eeae9b0055b8483570b3500f852ab40b8210159cb7ad313672ed65b3a7R871). Exposing a more raw version like this would make it easy for users to create their own convenience functions, if they need to.

**Comment by borkdude** [comment]
I think the vector of map approach is promising. I'm going to release the version as it is now in the next babashka without adding anything and then wait for more feedback in this issue.

**Comment by lispyclouds** [comment]
I would second the vector of entry maps and a map of opts too. Maybe if we want to have everything as in the opts map including `:entries` would be my slightly more preferred way. Might go well with the keyword args in clojure 1.11 and have a similar UX as the zip cli?

**Comment by borkdude** [comment]
> Maybe if we want to have everything as in the opts map including :entries would be my slightly more preferred way. 

That's not the style that fs is in right now, I don't think it makes sense to change styles. Also, the current shape the fs function signatures are in work far better with `->` and `doto` than when you put everything in one big map:

``` clojure
(doto (-> (fs/create-temp-dir) (fs/file "dude")) 
  (spit "") (fs/set-posix-file-permissions "rw-------"))
```

**Comment by lispyclouds** [comment]
Yeah, what i was going for is the `file.zip` is the first positional param but the rest being in a map but i see the point of keeping it consistent.

**Comment by lread** [comment]
It might also be interesting to compare `zip` with `copy-tree` to see how much they overlap and if they might share options and/or influence one another.
