### ISSUE TITLE
copy-tree doesn't create nested destination directories

### ISSUE THREAD

**Issue by duzunov** [babashka/fs#42]
As discussed here: https://clojurians.slack.com/archives/CLX41ASCS/p1641396190148600
Tested with bb v0.7.0 and v0.7.3

Repro steps: 
```
➜  ~ mkdir foo
➜  ~ touch foo/bar1
➜  ~ touch foo/bar2
➜  ~ bb -e '(fs/copy-tree "foo/" "foo2/foo")'
----- Error --------------------------------------------------------------------
Type:     java.nio.file.NoSuchFileException
Message:  /Users/dimitaruzunov/foo2/foo
Location: <expr>:1:1
```

Expected result: to create the foo2 directory

Or to change the docstring:
`Copies entire file tree from src to dest. Creates dest if needed
using create-dirs, passing it the :posix-file-permissions
option. Supports same options as copy.`
https://babashka.org/fs/babashka.fs.html#var-copy-tree

**Comment by thiagokokada** [comment]
My 2c, I think it would be better if `copy-tree` had a explicit argument to create parents (it already seems to support options as the third parameter).

Something like `:create-dirs` or something.

BTW, Python can be an inspiration [here](https://docs.python.org/3/library/shutil.html#shutil.copytree).

**Comment by borkdude** [comment]
It seems python's copytree (same name!) creates the dest dir too.

```
$ python3 -c 'import shutil; shutil.copytree("foo", "foo2/foo")'
$ ls foo2/foo
bar1 bar2
```

**Comment by borkdude** [comment]
Also I think tools.build's copy-dirs does the same thing. Let's just do that by default (like the docstring already suggested). If people don't agree, we can disable that via an option later (if they complain).
