### ISSUE TITLE
Feature Request: Add something like cwd that returns the Current Working Directory

### ISSUE THREAD

**Issue by pwhittin** [babashka/fs#58]

**Comment by pwhittin** [comment]
Does something like `cd` make sense too?

**Comment by borkdude** [comment]
Should we name the function `cwd` or `working-dir` maybe?

Unfortunately `cd` cannot be supported in JVM-based environments (without dubious hacks):

https://stackoverflow.com/questions/840190/changing-the-current-working-directory-in-java

**Comment by borkdude** [comment]
The "java" way of getting the working dir:

```
(System/getProperty "user.dir")
```

**Comment by pwhittin** [comment]
Using 
```
(System/getProperty "user.dir")
```
refers to the directory from which Java was started.

From `bb`'s perspective where is this directory?

**Comment by borkdude** [comment]
The directory where the `bb` binary was started.

**Comment by pwhittin** [comment]
I guess `working-directory` makes sense.
