### ISSUE TITLE
split-ext/extension fail on files with trailing space on windows

### ISSUE THREAD

**Issue by jjttjj** [babashka/fs#63]
It seems that this works on linux but on windows fails.
```clojure
(spit "test .txt" "hi")
(fs/extension "test .txt")
```
The exception thrown is
```
InvalidPathException Trailing char < > at index 4: test 
	sun.nio.fs.WindowsPathParser.normalize (WindowsPathParser.java:191)
	sun.nio.fs.WindowsPathParser.parse (WindowsPathParser.java:153)
	sun.nio.fs.WindowsPathParser.parse (WindowsPathParser.java:77)
	sun.nio.fs.WindowsPath.parse (WindowsPath.java:92)
	sun.nio.fs.WindowsFileSystem.getPath (WindowsFileSystem.java:232)
	java.io.File.toPath (File.java:2396)
	babashka.fs/as-path (fs.cljc:39)
	babashka.fs/as-path (fs.cljc:34)
	babashka.fs/path (fs.cljc:53)
	babashka.fs/path (fs.cljc:47)
	babashka.fs/split-ext (fs.cljc:728)
	babashka.fs/split-ext (fs.cljc:720)
```

This is due to the call to `path` on something with a trailing space, ie `"test "`, [here](https://github.com/babashka/fs/blob/68b42dd1b6ee22cbcca6e6a807cfb079b608f033/src/babashka/fs.cljc#L728), this is an invalid path in windows, so it makes sense that calling `path` on that should throw on windows. `"test .txt"` as a path is valid on windows or at least it works with the rest of api. 

I'm not quite sure what the correct behavior here for  `extension` should be though. Figured I would report it and see what you think.

**Comment by borkdude** [comment]
I think we should probably just make this less reliant on the Path stuff, since it's basically just string manipulation.
