### ISSUE TITLE
read-all-lines fails when encoding not UTF-8

### ISSUE THREAD

**Issue by mcuervoe** [babashka/fs#64]
The function read-all-lines fails when the encoding is not UTF-8

With the file attached, [iso-8859.txt](https://github.com/babashka/fs/files/8744005/iso-8859.txt), the function produces this error:

(fs/read-all-lines (fs/file "iso-8859.txt"))
: Input length = 1 user 

If you enclose in a try-catch, the exception is java.nio.charset.MalformedInputException

(tested with babashka  v0.8.2)

Ideally, the function should provide an encoding optional param to deal with these cases.

**Comment by borkdude** [comment]
@mcuervoe Fixed :)

https://github.com/babashka/fs/blob/master/API.md#read-all-lines
