### ISSUE TITLE
Add dir-name

### ISSUE THREAD

**Issue by dbohdan** [babashka/fs#80]
[dirname(1)](https://linux.die.net/man/1/dirname) is a common command in shell scripts. It would be convenient to have its direct equivalent in babashka.fs. It would be also nice to have something that [functioned like](https://github.com/corasaurus-hex/fs/blob/master/test/corasaurus_hex/fs_test.clj#L109) `corasaurus_hex.fs/split-path`. I don't think they are redundant, since a dirname function would handle a path with no parent directory specially (returning `"."`). Joker, for example, has [`joker.filepath/dir`](https://candid82.github.io/joker/joker.filepath.html#dir) as well as `split` and `split-list`.

**Comment by borkdude** [comment]
OK, PR welcome for `dir-name` (as we have `file-name`, I think the hyphen would be ok?)

Note that `seq` works on the result of `fs/path` to split the components, but we could add this as a built-in.

I believe we already have `split-list` as `split-paths` in fs.

**Comment by dbohdan** [comment]
> Note that `seq` works on the result of `fs/path` to split the components, but we could add this as a built-in.

Oh, I didn't realize this. Thanks for explaining! And there turns out to be `fs/components`, which works like `split-path` except for the return type. Sorry I didn't look thoroughly enough before filing an issue. I missed it in `API.md`, probably because other file path APIs had primed me to look for different function names. (Maybe it needs a Ctrl+f-friendly note like "Use this to split a path.")

While I can't right now, I will PR `dir-name` when I can. (I agree it needs a hyphen.)

**Comment by borkdude** [comment]
On second thought: `dir-name` is already kind of there as: `(-> file fs/parent str)`. `parent` is the Java terminology of getting the parent directory from a file and `str` is the way of turning a file or path into a string. Not sure if we need to add `(defn dir-name [file] (-> file fs/parent str))`?

We could also add a cheat sheet of bash terminology -> fs terminlogy. 

cc @pesterhazy

**Comment by borkdude** [comment]
> except for the return type

You can fix this by doing `(map str ...)`.

**Comment by pesterhazy** [comment]
Gave it a try here https://github.com/pesterhazy/presumably/blob/master/posts/howto-babashka.md#find-project-folder

**Comment by dbohdan** [comment]
Oops, I missed not one but two of the two functions I wanted. :-) With `fs/parent` there is no need for `fs/dir-name`. If nobody disagrees, I suggest closing the issue.

> We could also add a cheat sheet of bash terminology -> fs terminlogy.

This is a great idea. Thanks for starting one, @pesterhazy.

**Comment by borkdude** [comment]
I mentioned `dirname` in the docs of `parent` now.

**Comment by felixdo** [comment]
parent is alright, but one has to be careful: (parent "hello.clj") returns nil, while dirname "hello.clj" is '.'

**Comment by borkdude** [comment]
We could change that perhaps
