### ISSUE TITLE
fs/extension handles paths with dot incorrectly

### ISSUE THREAD

**Issue by dbohdan** [babashka/fs#81]
```sh
> bb -e '(fs/extension "/foo/example.com/data")'
"com/data"
> bb --version
babashka v1.0.167
```

**Comment by dbohdan** [comment]
The current fix is IMO wrong. It changes `split-ext` from a pure function that operates on abstract paths to one whose result depends on the state of your filesystem, which is undesirable. It doesn't help you with remote or abstract paths. Instead, it would be better if it just made sure the last `.` in the path was after the last `/`.

**Comment by borkdude** [comment]
@dbohdan I agree with that, I misunderstood the original issue

**Comment by borkdude** [comment]
Done
