### ISSUE TITLE
`babashka.fs/glob` crashes when encountering permission errors

### ISSUE THREAD

**Issue by teodorlu** [babashka/fs#89]
On my Mac, I get the following behavior:

```
user=> (babashka.fs/glob "/private" "**/deps.edn")
java.lang.Exception: Visiting /private/etc/cups/certs failed [at <repl>:6:1]
```

I use `babashka.fs/glob` to find all `deps.edn` files in a subfolder in `neil-quickadd`. In my case, I'd prefer ignoring files and folders with permission errors.

https://github.com/teodorlu/neil-quickadd/blob/7bb1629670966d4e40adf458bc157f08eb2dc8f1/src/teodorlu/neil_quickadd.clj#L31

The glob folder traversal logic appears to be in `babashka.fs/match`:

https://github.com/babashka/fs/blob/master/src/babashka/fs.cljc#L250-L314

**Comment by borkdude** [comment]
Fixed in v0.2.16. You can load that version in babashka as follows: `(require '[babashka.fs] :reload)` until the following release of babashka.
